name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js '23.x'
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'npm'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '8.0'
        mongodb-replica-set: test-rs
        mongodb-port: 27017
    
    - name: NPM ci
      run: npm ci
    
    - name: Start Test Server
      run: |
        npm run build --if-present \
        npm run start:test & \
        sleep 5
  
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Tests
        run: | 
          npm run test:unit \
          npm run test:integration
  
  trigger_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Trigger CD Pipeline
      if: success()
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref": "main"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/CD.yaml/dispatches