# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js '23.x'
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'npm'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '8.0'
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - run: npm ci
    - run: npm run build --if-present
    - run: npm run start:test &
    - run: sleep 10
    - run: npm test
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # - name: Get the version tag
      #   id: version
      #   run: |
      #     VERSION=$(git describe --tags --abbrev=0)  # Get the latest Git tag as the version
      #     echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store it as an environment variable

      - name: Zip Files
        run: zip -r "./builds/app.zip" . -x "*.git*"

      - name: Upload zip to S3
        run: |
          aws s3 cp "./builds/app.zip" s3://your-bucket-name/path/to/upload/${VERSION}.zip
      # - name: Sync files to S3 bucket
      #   run: aws s3 sync . s3://acebook-node-citation-bucket --delete --exclude ".github/*"


